name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run survey repo script
        run: |
          export
          ./ci/survey_repo.sh
